Repository Chris-plus-alphanumericgibberish/dNAO, pull requests merged in 2020-04, with the labels that each got.

#459 Vision backend improvements and misc fixes
  include/vision.h
  include/youprop.h
  src/mon.c
  src/vision.c
Labels: bug (minor), enhancement

#460 Oops, broke this last time I touched it
  src/xhity.c
Labels: bug (major)

#461 Fix some issues with hidden monsters and mimics
  include/extern.h
  src/mon.c
  src/xhity.c
  src/xhityhelpers.c
Labels: bug (minor)

#462 Limit temple-priest-lightning to once per global turn
  src/priest.c
Labels: balance (minor)

#463 Fix crash
  src/objnam.c
Labels: bug (major)

#464 Artifact Gift Requirements
  include/artifact.h
  include/artilist.h
  src/artifact.c
Labels: bug (minor), enhancement

#465 Fix typo: breath->breathe
  src/region.c
Labels: bug (minor)

#466 Fix shatterproof/fixed being IDed when id-ing rustproofness
  src/wield.c
Labels: bug (minor)

#467 Oops, re-remove poison instadeath
  src/xhity.c
Labels: bug (major)

#468 Automatically free yourself u.ustuck if grabber/grabee is away
  src/hack.c
Labels: bug (major)

#469 Move some parts of mksobj around
  src/mkobj.c
Labels: bug (minor)

#470 Don't reprint magic chest bolting message
  src/lock.c
Labels: bug (minor)

#472 Re-add code that uses ovar1 to specify skill for mass-shadow ammo
  src/projectile.c
Labels: bug (minor)

#471 Fix copy-paste error
  include/artilist.h
Labels: bug (minor)

#475 Fix unintentional catsight
  src/mon.c
  src/vision.c
Labels: bug (major)

#478 Upgrade rndshape() to take a specification function
  include/extern.h
  src/makemon.c
  src/mon.c
Labels: balance (minor), enhancement

#481 In hmon(), magr must be checked before being used.
  src/xhity.c
Labels: bug (major)

#482 Nerf vorpal weapons [vs bosses]
  src/artifact.c
Labels: balance (minor)

#483 Fix lichen corpse weight not being set
  src/makemon.c
Labels: bug (minor)

#484 Hide weapon-is-ineffective message if it is lethal
  src/xhity.c
Labels: bug (minor)

#487 The permonst array must be updated before any monsters can be loaded
  src/mondata.c
  src/restore.c
Labels: bug (major)

#488 Actually use undiscovered_artifact() for if we know things about arti…
  src/invent.c
  src/objnam.c
Labels: bug (minor)

#491 Autons do not elevate all autons on level on death.
  src/mon.c
Labels: bug (major)

#493 Fix mtmp/axus copy-paste error
  src/mon.c
Labels: bug (major)

#495 Steam vortices shouldn't pummel with debris
  src/xhity.c
Labels: bug (minor)

#497 Fix mvm casting feedback bugs.
  src/mcastu.c
Labels: bug (minor)

#498 Fix empty lightsabers crashing
  src/apply.c
  src/zap.c
Labels: bug (minor)

#500 Give the Marauder's Map an appearance
  include/artilist.h
Labels: enhancement

#502 Anger the watch when forcing doors (like picking locks)
  include/extern.h
  src/lock.c
  src/monmove.c
Labels: enhancement

#503 Bugfixes: your zaps, monster zaps
  src/mthrowu.c
  src/xhity.c
  src/zap.c
Labels: bug (major)

#504 fix messages for reading conf monster
  src/read.c
Labels: bug (minor)

#505 Add some more artifact names
  include/artilist.h
Labels: enhancement

#507 `stop_occupation()` should interrupt multi-tile movements
  src/allmain.c
Labels: bug (minor), enhancement

#525 Fix missing behaviour for almost-POT_POLY chameleon, mimic blood
  src/potion.c
Labels: bug (minor)

#526 Hitting peacefuls with a `c` corpse angers them
  src/xhity.c
Labels: bug (minor)

#532 Fix duplicate-ls-catcher crashing
  src/light.c
Labels: bug (major)

#533 Remove lightsource from starlight when diluting
  src/potion.c
Labels: bug (minor)

#534 Fractured don't have eyes, but can still use some gazes
  include/extern.h
  src/mondata.c
  src/xhity.c
Labels: enhancement

#535 Patch lightsaber dipping
  include/obj.h
  src/artifact.c
Labels: bug (minor), enhancement

#537 Even more potion of starlight fixes
  src/o_init.c
  src/potion.c
  src/steal.c
  src/zap.c
Labels: bug (minor)

#538 Fix crash on throwing `c` corpse/egg upwards and being hit
  src/xhity.c
Labels: bug (major)

#541 Oops, Drow cannot use standard zombification.
  src/role.c
Labels: bug (minor)
