Repository Chris-plus-alphanumericgibberish/dNAO, pull requests merged in 2020-10, with the labels that each got.

#1206 Armor tweaks
  include/obj.h
  include/objclass.h
  src/objects.c
Labels: balance (major)

#1208 Reduce Poison, Filth instakill damage; rewrite Plague's effect.
  include/artifact.h
  src/artifact.c
  src/xhity.c
Labels: balance (minor)

#1209 Fix null mdef segfault
  src/mcastu.c
Labels: bug (major)

#1210 Dividing word can only instakill <400hp enemies
  src/spell.c
Labels: balance (minor)

#1212 Poly while in armor-poly form (dragon, lion) returns you to base form
  src/polyself.c
Labels: bug (minor)

#1213 Don't use un-ID'd arti gem appearances for lightsabers
  src/objnam.c
Labels: bug (minor)

#1214 Make Nameless Horrors difficulty 40
  src/mondata.c
  src/restore.c
  src/u_init.c
Labels: balance (minor), bug (minor)

#1215 New artifact: Apotheosis Veil
  src/artilist.c
  src/spell.c
Labels: enhancement

#1216 Remove objects' existing name when individually naming
  src/do_name.c
Labels: bug (minor)

#1217 Check that spiritPOrder != -1 where necessary.
  src/spell.c
Labels: bug (major)

#1218 Fix more unguarded &mons[otmp->corpsenm] checks in eat.c
  src/eat.c
Labels: bug (major)

#1219 Fix memory-out-of-bounds error with travel algorithm
  src/hack.c
Labels: bug (major)

#1220 Fix off-by-one error in safety check
  src/botl.c
Labels: bug (major)

#1221 Calculate maximum hp/pw from levelup and cap current values AFTER add…
  src/exper.c
Labels: bug (minor)

#1222 New artifact: The Helm of Undeath
  src/artilist.c
  src/end.c
  src/polyself.c
Labels: enhancement

#1223 Properly find player's average DR
  src/do_wear.c
Labels: bug (minor)

#1224 Fix yet another mcastu crash
  src/mcastu.c
Labels: bug (major)

#1225 Fix impossible moving to a new level that's full
  src/do.c
Labels: bug (minor)

#1226 Check that rectangle corners are in-bounds
  src/mkmaze.c
Labels: bug (minor)

#1228 Check thrownobj on 2nd hand for monsters firing
  src/projectile.c
Labels: bug (minor)

#1229 Fix off-by-one error, causing bad room removal attempts
  src/mkmaze.c
  src/sp_lev.c
Labels: bug (minor)

#1230 Oops, duh
  src/zap.c
Labels: bug (minor)

#1231 Fix use-after-free for monsters using lizard corpses
  src/muse.c
Labels: bug (minor)

#1232 Add handling to poly_obj a monster's equiped weapon
  src/zap.c
Labels: bug (minor)

#1233 Check engulfer is alive before placing
  src/xhity.c
Labels: bug (minor)

#1235 Fix use after free from light disintegration
  src/worn.c
Labels: bug (minor)

#1236 Revert changes made to remove_rooms(); use different Spire-Dispensary…
  dat/dngnch1.def
  dat/dngnch2.def
  dat/dngnch3.def
  src/mkmap.c
Labels: bug (major)

#1238 Fix crash when attempting to replace object in magic chest chain
  src/mkobj.c
Labels: bug (major)

#1239 Improve logic on xengulfy snuffing lightsources
  src/xhity.c
Labels: enhancement

#1240 Change ranged weapon balance
  src/artilist.c
  src/projectile.c
  src/xhity.c
Labels: balance (major)

#1241 Add new flag, MF (Monster Fighting)
  include/artifact.h
  include/extern.h
  include/monflag.h
  include/permonst.h
  src/artifact.c
  src/artilist.c
  src/mondata.c
  src/monst.c
  src/mthrowu.c
  src/projectile.c
  src/xhity.c
Labels: balance (minor), enhancement (complex)

#1242 Monsters get their +melee damage to ranged as well
  src/projectile.c
Labels: balance (major)

#1243 Don't enchant rings of wishes
  src/pray.c
Labels: bug (minor)

#1244 Equality was backwards
  src/eat.c
Labels: bug (minor)

#1245 Change `exist_artifact` into `art_already_exists` and `art_already_ex…
  include/artifact.h
  include/extern.h
  src/artifact.c
  src/bones.c
  src/do_name.c
  src/fountain.c
  src/pray.c
Labels: bug (minor), enhancement

#1247 Fix MF_flags breaking artifact warning
  src/artilist.c
Labels: bug (minor)
