Repository Chris-plus-alphanumericgibberish/dNAO, pull requests merged in 2020-12, with the labels that each got.

#1261 Catch null pointer write
  src/mkroom.c
Labels: bug (minor)

#1264 Fix eggfault
  src/xhity.c
Labels: bug (major)

#1270 Fix read after free from destroyed wand engraving
  src/engrave.c
Labels: bug (minor)

#1271 Set mimic colours for cursed detection
  src/detect.c
Labels: bug (minor)

#1272 Rewrite obj_to_glyph as function
  include/decl.h
  include/display.h
  include/extern.h
  src/decl.c
  src/display.c
Labels: enhancement

#1276 Limit polymorphs of template'd monsters to reasonably retain template
  include/extern.h
  include/hack.h
  include/mondata.h
  src/artifact.c
  src/do_name.c
  src/dog.c
  src/dogmove.c
  src/makemon.c
  src/mcastu.c
  src/mon.c
  src/mondata.c
  src/monmove.c
  src/muse.c
  src/music.c
  src/pager.c
  src/potion.c
  src/pray.c
  src/sounds.c
  src/spell.c
  src/teleport.c
  src/trap.c
  src/xhity.c
  src/xhityhelpers.c
  src/zap.c
Labels: enhancement

#1278 Fix worn object interactions when changing material
  src/mkobj.c
Labels: bug (minor)

#1280 Multishot uses the launcher's skill, when ammo/launcher differ in skill
  src/projectile.c
Labels: bug (minor)

#1281 Fix dtype/skill mixup
  src/objects.c
Labels: bug (minor)

#1282 Split gcrownu off into its own file, rewrite it.
  GNUmakefile
  include/extern.h
  src/cmd.c
  src/crown.c
  src/pray.c
Labels: bug (minor), enhancement (complex)

#1283 More corpsenm safety
  include/obj.h
  src/dog.c
  src/eat.c
Labels: bug (minor)

#1284 Fix shks merging with zombies when trying to block the door
  src/priest.c
Labels: bug (minor)

#1285 Don't let AD_WEBS replace traps
  src/xhity.c
Labels: bug (minor)

#1286 Drop trap ammo when replacing traps
  src/trap.c
Labels: balance (minor)

#1287 Add more artifact encyc entries
  dat/data.base
  src/artilist.c
Labels: enhancement

#1298 Oops fix bracketing
  src/xhity.c
Labels: bug (major)

#1288 Make boulders scary
  src/dothrow.c
  src/projectile.c
  src/weapon.c
  src/xhity.c
Labels: balance (major), bug (minor)

#1289 Fix spacing
  src/weapon.c
Labels: bug (minor)

#1290 Some backend cleanup about templates/factions
  include/monst.h
  src/makemon.c
  src/mondata.c
Labels: enhancement

#1291 Tie groupsize of zombies to the inverse of their strength
  src/makemon.c
Labels: balance (minor)

#1293 Player Vampires should get nutrition from draining foes
  src/xhity.c
Labels: bug (minor)

#1295 Restrict farcasting Clairvoyance on no-map levels
  src/spell.c
Labels: balance (minor)

#1297 Show weapon skill on inspection.
  include/extern.h
  src/invent.c
  src/weapon.c
Labels: enhancement

#1299 Don't immediately null weapon, it's needed for messaging
  src/xhity.c
Labels: bug (major)

#1300 Fix merge conflict
  src/crown.c
  src/makemon.c
Labels: bug (major)

#1301 Use a proper untame() function to remember to clean MX_EDOG as needed
  include/extern.h
  src/allmain.c
  src/apply.c
  src/artifact.c
  src/dog.c
  src/dogmove.c
  src/makemon.c
  src/minion.c
  src/mon.c
  src/muse.c
  src/pray.c
  src/priest.c
  src/restore.c
  src/sounds.c
  src/wizard.c
  src/xhity.c
  src/xhityhelpers.c
  src/zap.c
Labels: bug (minor)

#1302 Call uwepgone() when appropriate
  src/xhity.c
Labels: bug (major)

#1303 Check u.spiritPOrder[i] != -1
  src/spell.c
Labels: bug (minor)

#1304 Set *weapon_p before early returns
  src/xhity.c
Labels: bug (minor)

#1305 Use players' InvElem_resistance macros for xhity InvElem_resist(mdef)
  include/xhity.h
Labels: bug (minor)

#1307 Better handle photography of minors
  src/zap.c
Labels: bug (minor)

#1309 Better align how you can self-inspect and monsters can see binder signs
  src/cmd.c
  src/shk.c
Labels: bug (minor)

#1312 Undo most of previous potion change in favour of a smaller change
  src/xhity.c
Labels: bug (minor)

#1313 Tweak arti prices
  src/shk.c
Labels: balance (minor)

#1314 Use a global to prevent rolling boulder traps triggering others
  src/trap.c
Labels: bug (minor)

#1292 Add different "fail" messages to Necronomicon if LAST_PAGE
  src/artifact.c
Labels: enhancement

#1315 Boulder fixes and nerfs
  include/obj.h
  src/xhity.c
Labels: balance (minor), bug (minor)

#1316 Possibly fix that weird merged-rooms-wall-lighting bug?
  src/mklev.c
Labels: bug (minor)

#1318 Properly message sleep rays.
  src/zap.c
Labels: bug (minor)

#1319 Fix unintentional addition of +basedmg to PotV and Magicbane-like weapons
  src/artifact.c
Labels: balance (minor), bug (minor)

#1324 Fix bugs in monster spell targeting
  src/mcastu.c
Labels: bug (minor)

#1326 Don't check mtmp->tame here, it often is already 0
  src/dog.c
Labels: bug (minor)

#1329 AoE Buff spells should exclude grudges
  src/mcastu.c
Labels: bug (minor)

#1330 Patch bag contents merging
  src/do.c
Labels: bug (minor)

#1331 Make offhand attack even when mainhand misses
  src/xhity.c
Labels: balance (minor)

#1332 Add description of the Annulus' special case for its bonus damage
  src/invent.c
Labels: bug (minor)

#1333 Re-set potion colour after changing potion->otyp
  src/potion.c
  src/trap.c
  src/zap.c
Labels: bug (minor)

#1335 Monsters appear at correct magic portal
  src/dog.c
Labels: bug (minor)

#1336 Check that monsters aren't dead yet before drowning them
  src/mon.c
Labels: bug (minor)

#1337 Fix monsters with AT_ARRW attacks "shoot!"ing nothing
  src/projectile.c
  src/xhity.c
Labels: bug (minor)

#1338 Androids can throw single Fluorite Octahedrons to return
  src/projectile.c
Labels: bug (minor)

#1339 Fix gigantic holes in untame() bugfix
  src/dog.c
  src/steed.c
Labels: bug (minor)

#1340 ID and mitigate potential corruptions of monster movement loop
  src/mon.c
Labels: bug (major)

#1341 Short-circuit mm_aggression() if magr and mdef are distant
  src/mon.c
Labels: enhancement

#1342 Fix black unicorns not teleporting away
  src/monmove.c
Labels: bug (minor)

#1343 Fix monster nightvision circles
  src/mon.c
Labels: bug (minor)

#1344 Fix a couple misc details
  src/projectile.c
  src/xhity.c
Labels: bug (minor)

#1346 Oops, forgot to add extern.h in the xfirey upgrade commit
  include/extern.h
Labels: bug (major)

#1348 Add guard for mstoning macro's corpsenm usage
  src/mon.c
Labels: bug (minor)

#1349 Correct some curses buffer overflows
  src/botl.c
  win/curses/cursmisc.c
Labels: bug (minor)

#1350 Double-check that magr lives after it makes each attack
  src/xhity.c
Labels: bug (minor)

#1352 Fix mazerooms being unable to place a door
  src/mkmaze.c
Labels: bug (minor)

#1353 Fix thrown potions yet again
  src/xhity.c
Labels: bug (major)

#1354 Check mtyp is valid
  src/mondata.c
Labels: bug (minor)

#1357 Fix rockets having R0 explosions if not youagr
  src/projectile.c
Labels: bug (minor)

#1358 Only forcibly re-set W_BALL/W_CHAIN for ball and chain
  src/projectile.c
Labels: bug (minor)

#1361 Fix typo
  src/artifact.c
Labels: bug (minor)

#1362 Check visibility of zaps before printing miss message.
  src/zap.c
Labels: bug (minor)

#1363 Only print Kusanagi no Tsurugi's fancy evade message for the player
  src/artifact.c
Labels: bug (minor)

#1364 Double-bladed lightsabers get 6x enchantment
  src/weapon.c
Labels: balance (major)

#1368 Gnomes get +2 to-hit
  src/xhity.c
Labels: balance (minor)

#1370 Update object colour when polymorphing it.
  src/zap.c
Labels: bug (minor)
