Repository Chris-plus-alphanumericgibberish/dNAO, pull requests merged in 2020-05, with the labels that each got.

#542 Binder spirit QoL and backend changes
  include/extern.h
  include/prop.h
  include/youprop.h
  src/artifact.c
  src/engrave.c
  src/sounds.c
  src/spell.c
  src/timeout.c
Labels: enhancement

#543 Add special case to catch "mindflayer" and "master mindflayer"
  src/mondata.c
Labels: enhancement

#545 Re-add missing Ahazu protection vs engulfing
  src/xhity.c
Labels: bug (minor)

#546 Re-add Otiax's OP 1/5 protection vs being hit
  src/xhity.c
Labels: bug (minor)

#547 Fix uninitiallized variable leading to segfault
  src/polyself.c
Labels: bug (major)

#548 Fix cockatrices not petrifying unprotectable attacks
  src/xhity.c
  src/xhityhelpers.c
Labels: bug (major)

#550 Check visibility of action for printing object destruction messages
  src/xhity.c
Labels: bug (minor)

#551 Add weapon damage types to item inspection
  include/extern.h
  src/invent.c
  src/weapon.c
  src/xhity.c
Labels: enhancement

#552 Change "ineffective" message to specify attack type
  src/xhity.c
Labels: enhancement

#553 Fix hemmorhagic thing's footsteps
  src/engrave.c
  src/monmove.c
Labels: bug (minor)

#555 Changes + Fixes to making torches
  src/potion.c
  src/timeout.c
Labels: bug (minor), enhancement

#557 Monsters follow the player better
  include/extern.h
  src/dogmove.c
  src/monmove.c
  src/track.c
Labels: enhancement

#558 Turns out, reusing one static array of object properties is NOT safe
  include/extern.h
  src/artifact.c
  src/invent.c
  src/worn.c
Labels: bug (major)

#561 Buff beartraps
  include/obj.h
  src/objects.c
  src/trap.c
  src/xhity.c
Labels: balance (minor)

#562 Fix mazes sometimes not being fully walked
  src/mkmaze.c
Labels: bug (major)

#563 Change xray backend; buff Shield of the Allseeing
  include/artifact.h
  include/artilist.h
  include/prop.h
  include/vision.h
  include/you.h
  include/youprop.h
  src/artifact.c
  src/pager.c
  src/timeout.c
  src/u_init.c
  src/vision.c
Labels: balance (minor)

#568 Change staff of necromancy + POTV reading messages
  src/invent.c
  src/read.c
Labels: enhancement

#569 Patch buff xiuhcoatl
  include/artilist.h
  src/artifact.c
  src/objnam.c
  src/weapon.c
Labels: balance (minor)

#570 Don't give monsters cav/ymir bonuses
  src/invent.c
  src/xhity.c
Labels: bug (minor)

#571 Split ^V leveltele menu into 2 inputs
  include/extern.h
  src/cmd.c
  src/dungeon.c
  src/teleport.c
Labels: enhancement

#572 Make Plague's invoke stronger
  src/xhity.c
Labels: balance (minor)

#573 Fix incorrect flag in Shelob's permonst entry
  src/monst.c
Labels: bug (minor)

#579 Need to check "no protection available" for mvm and mvu
  src/xhityhelpers.c
Labels: bug (minor)

#583 Add missing semicolon.
  src/weapon.c
Labels: bug (major)

#582 Only breath-attack sleep rays bypass reflection
  src/zap.c
Labels: balance (minor), bug (minor)

#585 Check that artifacts deal X damage type before messaging for X
  src/artifact.c
Labels: bug (minor)

#586 Nagas/mariliths/etc have a "rear region" like a snake, not a "leg".
  src/polyself.c
Labels: bug (minor)

#587 potion of speed auto-IDs if you got faster
  src/potion.c
Labels: enhancement

#588 Check if artifact is known before saying an item is fully IDed
  src/shk.c
Labels: bug (minor)

#589 Axus's attack is supposed to primarily check shock/drain resists
  src/xhity.c
Labels: bug (minor)

#591 Make Blade Singer's Saber unrestrict saber properly, not spear
  src/pray.c
Labels: bug (minor)

#593 Adjust Free Action + Stoning interaction
  src/mcastu.c
  src/timeout.c
Labels: balance (major)

#595 "Killed by foo" end message should specifiy zombies/etc
  include/extern.h
  src/do_name.c
  src/end.c
Labels: bug (minor)

#596 Fix obvious Black Goat issues
  src/pray.c
Labels: bug (minor)

#597 Enhance engulf attacks and attackers
  include/extern.h
  src/hack.c
  src/xhity.c
Labels: enhancement

#598 Gun ammo bypasses resists
  src/objects.c
Labels: balance (minor)

#601 Fix panic
  src/xhity.c
Labels: bug (major)

#602 Fix uranium imp crash
  src/xhity.c
Labels: bug (major)

#603 magr can move into/out of LoS when engulfing
  src/xhity.c
Labels: bug (major)

#605 Fix copy-paste error in Sol Valtiva making at avoid grasp
  include/artilist.h
Labels: bug (major)

#606 Being gifted the Golden Sword of Y'ha-Talla should unrestrict Whip skill
  src/pray.c
Labels: bug (minor)

#607 Re-enable artifact tiers affecting god gifts
  src/pray.c
Labels: balance (major)

#608 Fix zombie attacks
  src/mondata.c
Labels: bug (minor)

#609 Fix backwards silver-dipping logic
  src/potion.c
Labels: bug (minor)

#611 Fix panic on engulfing petrifier
  src/xhity.c
Labels: bug (major)

#612 Allow the Wallet of Perseus to be gifted and generate randomly
  include/artilist.h
Labels: balance (minor)

#616 Fix ambiguous bracketing causing error
  src/mondata.c
Labels: bug (minor)

#617 Adjust damage calculations on high-level attack spells
  src/spell.c
Labels: balance (minor)

#618 Mother Hydra and Father Dagon get gear.
  src/makemon.c
Labels: bug (minor)

#619 Fix double "hits" message
  src/artifact.c
Labels: bug (minor)

#620 Ki-rin don't have hands
  src/monst.c
Labels: bug (minor)

#621 Fix martial arts aids
  src/xhity.c
Labels: bug (minor)

#622 Missed projectiles need to call wakeup2() to aggro mdef
  src/projectile.c
Labels: bug (minor)

#624 Re-add Edder-symbol signet rings increasing unarmed damage
  src/xhity.c
Labels: bug (minor)

#625 Fix offset in array index error
  src/sounds.c
Labels: bug (major)

#626 Disable "Mirror Walk" power
  src/spell.c
Labels: bug (minor)

#627 Fix Genocide blasting all races on level
  src/artifact.c
Labels: bug (minor)

#628 Bandaid-fix artifacts in monster inventories being destroyable
  src/zap.c
Labels: bug (minor)

#629 Rewrite Nudzirath's "Mirror Shatter" power
  include/extern.h
  include/hack.h
  src/projectile.c
  src/spell.c
  src/xhity.c
  src/zap.c
Labels: bug (minor), enhancement

#631 makemon() should always place monsters safely
  include/extern.h
  include/hack.h
  src/makemon.c
  src/mon.c
  src/mondata.c
  src/teleport.c
Labels: bug (minor)

#632 Axus' auton spawns get no inventory
  src/mon.c
Labels: balance (minor)

#633 Note: dragon breaths go at the front of their attack chain.
  src/mondata.c
Labels: bug (minor)

#634 Discover artifacts on death
  src/end.c
Labels: bug (minor)

#635 Fix warning
  src/pray.c
Labels: bug (minor)

#637 Fix bad spacing in slip message
  src/xhity.c
Labels: bug (minor)

#638 Fix Marauder's Map vanishing from inuse
  src/read.c
Labels: bug (minor)

#630 Fix impossible() on failed teleport of eels
  src/teleport.c
Labels: bug (minor)

#640 Don't randomize Arc's starting pickaxe enchantment
  src/u_init.c
Labels: balance (minor)

#641 Increase tinning kit charges in starting inventory
  src/u_init.c
Labels: balance (minor)

#645 Set a dedicated buffer for killer in hmon.
  src/xhity.c
Labels: bug (minor)

#646 Initialize vis=0
  src/xhity.c
Labels: bug (minor)

#647 Fixes for Stormbringer
  src/artifact.c
Labels: bug (major)
