Repository Chris-plus-alphanumericgibberish/dNAO, pull requests merged in 2020-11, with the labels that each got.

#1249 Oops, re-add "bloodthirsty" flag to the Tsurugi of Muramasa
  src/artilist.c
Labels: bug (minor)

#1250 Fix two simple warnings
  src/end.c
  src/weapon.c
Labels: bug (minor)

#1251 Fix typo in comments
  src/artilist.c
Labels: bug (minor)

#1252 Oops, Chaos needs a spellcast in their attack chain
  src/monst.c
Labels: bug (minor)

#1254 Fact-check the Oracle's consultations.
  dat/oracles.txt
Labels: bug (minor)

#1255 Fact-check true rumors
  dat/rumors.tru
Labels: bug (minor)

#1256 Changes and fixes to offering up artifacts
  include/extern.h
  src/artifact.c
  src/sounds.c
Labels: balance (minor), bug (minor)

#1257 Plague doesn't use ovar1 anymore; update macro
  include/obj.h
Labels: bug (minor)

#1259 Catch axes before blades for artifact on-hit messages
  src/artifact.c
Labels: enhancement
