Repository Chris-plus-alphanumericgibberish/dNAO, pull requests merged in 2020-07, with the labels that each got.

#799 Fix dragon breaths being easily reflectable
  src/projectile.c
Labels: bug (minor), next version

#853 Nerf paralysis poison
  src/xhity.c
Labels: balance (major)

#873 Artifact potions aren't flagged in_use
  src/potion.c
Labels: bug (minor)

#874 Adjust fluorite octet
  include/artilist.h
  src/objnam.c
  src/projectile.c
Labels: bug (minor), enhancement

#877 Write xhity stoning gazes
  include/extern.h
  src/xhity.c
Labels: bug (minor)

#878 Use a proper "yours" parameter for ownership of clouds.
  include/extern.h
  include/flag.h
  src/allmain.c
  src/artifact.c
  src/mcastu.c
  src/mon.c
  src/monmove.c
  src/read.c
  src/region.c
  src/spell.c
  src/zap.c
Labels: enhancement

#879 Anger shk by forcing their doors down
  src/lock.c
Labels: bug (minor)

#880 Mirrorblades also add enchantment of weapon they are mirroring
  src/weapon.c
Labels: bug (minor)

#882 Show spirit slots of pen in self-inspection
  src/cmd.c
Labels: enhancement

#884 Add artifact_descriptors flag to show artifact details even when ID'd
  include/flag.h
  src/artifact.c
  src/invent.c
  src/objnam.c
  src/options.c
  src/potion.c
  src/sounds.c
Labels: enhancement

#885 Use proper set_material function, comment things
  src/do_name.c
Labels: bug (minor)

#886 Silence a couple xcasty warnings
  src/mcastu.c
Labels: bug (minor)

#887 Some small xcasty balance changes
  src/mcastu.c
Labels: balance (minor)

#888 Rename Death-Spear of Keptolo, adjust spell bonus
  include/artilist.h
  include/obj.h
  src/artifact.c
  src/spell.c
  src/wield.c
  src/xhity.c
  src/zap.c
Labels: bug (minor)

#889 Hiking boots increase carrycap regardless of BUC
  src/hack.c
Labels: balance (minor), bug (minor)

#890 Add 3.6 #tip command
  include/extern.h
  src/apply.c
  src/cmd.c
  src/makemon.c
  src/mkobj.c
  src/pickup.c
Labels: enhancement

#891 Don't push boulders when running
  src/hack.c
Labels: bug (minor)

#892 Spellbooks of Secrets are not unique
  src/mkobj.c
  src/o_init.c
  src/objects.c
  src/objnam.c
  src/write.c
Labels: bug (minor)

#894 Uncursing (spell, scroll, effigy) affects ridden steed's saddle
  src/apply.c
  src/read.c
Labels: bug (minor)

#895 Use proper method of giving dwarves carving tools
  src/u_init.c
Labels: bug (minor)

#896 Fix #look desc
  src/cmd.c
Labels: bug (minor)

#898 Fix Dirge logic
  src/xhity.c
Labels: bug (minor)

#899 Improve mongets to return obj pointer, so I can nerf legion devil wands
  include/extern.h
  src/makemon.c
Labels: enhancement

#901 Needs an exception in select_floor_artifact
  src/artifact.c
Labels: bug (minor)

#902 Buff shotguns vs zombies
  src/weapon.c
Labels: balance (minor)

#903 Prevent floor spawn of Marauder's Map for Pirates
  src/artifact.c
Labels: enhancement

#904 Improve monster ranged AI
  include/extern.h
  include/monattk.h
  src/monmove.c
  src/mthrowu.c
  src/xhity.c
Labels: bug (minor), enhancement

#908 Clean up targeting of xcasty in xhity, fix bugs
  src/monmove.c
  src/xhity.c
Labels: bug (major), bug (minor)

#912 Fix Marauder's Map not detecting contained, carried artifacts correctly
  src/detect.c
Labels: bug (minor)

#913 Be more careful about spellcasting attempts with no target
  src/mcastu.c
Labels: bug (minor)

#914 Fix trap ammo not being searched for timers
  src/shk.c
Labels: bug (major)

#915 Hopefully fix tty engulf stack overflow
  win/tty/wintty.c
Labels: bug (minor)

#916 Oops, `break` was breaking out of a different switch than expected
  src/timeout.c
Labels: bug (minor)

#917 Moving into self NOT okay, staying in place YES okay
  src/mon.c
Labels: bug (minor)

#919 Black web should not unbind for Anachrononauts
  src/timeout.c
Labels: bug (minor)

#920 Feature: abilities menu
  include/flag.h
  include/you.h
  src/cmd.c
  src/options.c
Labels: bug (minor), enhancement

#924 New mfind_target doesn't need pre-checking
  src/dogmove.c
Labels: bug (minor)

#926 Fix engulfer eating steed and moving under you
  src/xhity.c
Labels: bug (minor)

#928 Free otmp before calling mdrop_obj
  src/mcastu.c
Labels: bug (major)

#936 Only Oona should check oona-resist
  src/mthrowu.c
Labels: bug (minor)

#900 Macro Magic: applied on artilist
  include/artilist.h
  include/nerosmacromagic.h
Labels: enhancement (complex)

#939 Fix wishing for great claws of urdlen
  src/objnam.c
Labels: bug (minor)

#940 Fix Dantalion applying Int damage
  src/weapon.c
  src/xhity.c
Labels: bug (minor)

#943 Improve macro magic
  include/artilist.h
  include/macromagic.h
Labels: enhancement

#945 Cancelled monsters don't rise from the dead on their own
  src/mkobj.c
Labels: balance (minor)

#961 Fix multistriking weapons
  include/xhity.h
  src/xhity.c
Labels: bug (minor)

#960 Add more tip interactions
  src/pickup.c
Labels: enhancement

#964 Apply DR before HalfPhys/DamageTypeResistance
  src/xhity.c
Labels: balance (major)

#963 Improve find-obj-desc functions in o_init.c
  include/extern.h
  src/apply.c
  src/artifact.c
  src/ball.c
  src/dig.c
  src/do_wear.c
  src/dokick.c
  src/hack.c
  src/mcastu.c
  src/mkobj.c
  src/mondata.c
  src/o_init.c
  src/seduce.c
  src/sounds.c
  src/spell.c
  src/steed.c
  src/trap.c
  src/xhity.c
Labels: enhancement

#965 Horror changes and a new nasty Horror type
  include/ehor.h
  include/extern.h
  include/mondata.h
  src/makemon.c
  src/mondata.c
  src/monst.c
  src/muse.c
  src/restore.c
  src/u_init.c
Labels: balance (minor), enhancement

#966 De-stupidify parts of macromagic
  include/macromagic.h
Labels: enhancement

#967 Remove longinus double damage
  include/artilist.h
Labels: bug (minor)

#968 Clean up some hmon2point0 calls
  include/extern.h
  src/apply.c
  src/ball.c
  src/do.c
  src/explode.c
  src/projectile.c
  src/trap.c
  src/xhity.c
Labels: enhancement

#971 Option to always show arti name
  include/flag.h
  src/objnam.c
  src/options.c
Labels: enhancement

#981 Fix twoweaponing shadowblades
  src/xhity.c
Labels: bug (minor)

#978 Apply macromagic on objects.c
  include/extern.h
  include/macromagic.h
  include/obj.h
  include/objclass.h
  src/artifact.c
  src/invent.c
  src/lock.c
  src/mkobj.c
  src/objects.c
  src/objnam.c
  src/shk.c
  src/weapon.c
  src/write.c
  src/xhity.c
Labels: enhancement (complex)

#982 Improve tracking in mvm grudging
  src/monmove.c
Labels: bug (minor)

#984 Fix mistakes in my previous commits
  src/explode.c
  src/hack.c
  src/o_init.c
Labels: bug (minor)

#985 Fix attempting to levelport >13 in Law being bad
  src/teleport.c
Labels: bug (major)

#986 Limit random levelports in upwards-direction dungeons
  src/teleport.c
Labels: bug (minor)

#987 Misc mability fixes
  include/you.h
  src/cmd.c
Labels: bug (minor)

#988 Add Naome reflection message
  src/muse.c
Labels: bug (minor)

#989 Nerf twoweaponed unarmed via STR damage and skill damage changes
  include/extern.h
  src/weapon.c
  src/xhity.c
Labels: balance (major)

#990 Extcmd android_combo(), allowing direct keybind
  include/extern.h
  src/cmd.c
  src/xhity.c
Labels: enhancement

#991 Set colours of wished-for gem items
  src/objnam.c
Labels: bug (minor)

#992 Don't warn for re-reading if you're trying the ward
  src/spell.c
Labels: bug (minor)

#994 Use a different letter for the Red Word
  src/polyself.c
Labels: bug (minor)

#995 Don't snuff sunrods
  src/light.c
Labels: bug (minor)

#996 Specify armor dr slots in objects.c
  include/objclass.h
  include/you.h
  src/do_wear.c
  src/objects.c
  src/worn.c
Labels: enhancement

#979 Add basic handling for AD_STAR ray spell
  src/spell.c
  src/zap.c
Labels: bug (minor)

#1002 Fix spell-swapping bug in tty version of spellmenu
  src/spell.c
Labels: bug (minor)

#1004 Fix bug with shadowsteel items, orthos, when swallowed
  include/extern.h
  src/allmain.c
  src/light.c
  src/worn.c
Labels: bug (minor)

#1006 You *attacking* something with a bladed shadow poisons *you*
  src/xhity.c
Labels: bug (minor)

#1009 Remove buzz(), zhitm(), zhitu(); replace with zap(), zhit().
  include/extern.h
  include/hack.h
  include/zap.h
  src/artifact.c
  src/dothrow.c
  src/mcastu.c
  src/mon.c
  src/monst.c
  src/muse.c
  src/music.c
  src/polyself.c
  src/priest.c
  src/projectile.c
  src/spell.c
  src/timeout.c
  src/worn.c
  src/zap.c
Labels: enhancement (complex)

#1011 Dropping a bag on an altar will BUC-id its contents
  src/do.c
Labels: enhancement

#1012 Livelog Acererak's death
  src/mon.c
Labels: bug (minor)

#1013 Reduce stat abuse, fix things preventing exercise
  src/attrib.c
Labels: balance (minor), bug (minor)

#1014 Fix scrolls of consecration
  src/read.c
Labels: bug (minor)
