Repository Chris-plus-alphanumericgibberish/dNAO, pull requests merged in 2020-06, with the labels that each got.

#653 Fix disintegration xhity death message
  src/xhity.c
Labels: bug (minor)

#656 Sets of crow talons are innately plural.
  src/artifact.c
Labels: bug (minor)

#649 fix bug that was making certain glyphs unwishable
  src/objnam.c
Labels: bug (minor)

#654 Fix "Call a tiny mysterious magenta potion:" message
  src/potion.c
Labels: bug (minor)

#658 Fix unseen monsters interrupting player
  src/xhity.c
Labels: bug (minor)

#661 Fix (null)-named artifacts appearing in the end score
  src/end.c
Labels: bug (minor)

#665 Fix Tecpatl of Huhelotl, which was completely broken
  src/artifact.c
Labels: bug (major)

#650 Quick-return BEFORE opening a menu.
  src/apply.c
Labels: bug (major)

#655 Reading the Blinding Glyph should grant Intrinsic Flight
  src/do_wear.c
  src/read.c
Labels: bug (minor)

#667 Re-add Great Claws of Urdlen increasing unarmed damage multiplier
  src/xhity.c
Labels: bug (minor)

#670 Fix drow nobles not getting first gift.
  src/artifact.c
Labels: bug (major)

#673 Fix Naome's bad MG_ flags
  src/monst.c
Labels: bug (minor)

#677 Fix Orcus Wand
  include/artilist.h
  src/weapon.c
  src/xhity.c
Labels: bug (minor)

#678 Change the message given when fully draining a spellbook
  src/eat.c
Labels: enhancement

#680 Fail GRACEFULLY
  src/sp_lev.c
Labels: bug (major)

#681 The "do not match" strncmpi does NOT set `l = ##".
  src/objnam.c
Labels: bug (major)

#691 Update shk symbol when angered
  src/shk.c
Labels: bug (minor)

#694 Fix impossible and bad obj_resist odds
  src/timeout.c
Labels: bug (minor)

#695 Fix fallthru not working as intended
  src/xhity.c
Labels: bug (minor)

#698 Formally ID objects that grant flight, displacement on mon use
  src/worn.c
Labels: bug (minor), enhancement

#699 Oops, re-add execising DEX on hit
  src/xhity.c
Labels: bug (major)

#707 Misc fixes on what things are wieldable
  src/weapon.c
  src/xhity.c
Labels: bug (minor)

#708 Rewrite doUseComponents to fix read-after-free and be more sane
  src/apply.c
Labels: bug (minor)

#709 Fix passives not procing when mdef died
  src/xhity.c
Labels: bug (minor)

#712 Change choking on food to a delayed instakill
  src/eat.c
  src/end.c
  src/timeout.c
Labels: balance (minor), enhancement

#713 kusanagi can be picked up safely
  src/artifact.c
  src/do_name.c
  src/wield.c
Labels: enhancement

#715 Fix impossible() in library of ill-regard monster placement
  src/mkmaze.c
Labels: bug (minor)

#716 Fix Alhoons, wide-clubbed tentacles, being summonable.
  src/monst.c
Labels: bug (minor)

#718 Jade stones do jade searing
  src/xhityhelpers.c
Labels: bug (minor)

#719 Fix unsafe d() call
  src/polyself.c
Labels: bug (major)

#720 'loose' -> 'lose'
  src/pray.c
Labels: bug (minor)

#728 Kraken do belong in Ill-Regard.
  src/mkmaze.c
Labels: bug (minor)

#729 Re-hire Vault guards
  src/monst.c
Labels: bug (major)

#733 Rotate char buffer for s_suffix
  src/hacklib.c
Labels: bug (minor)

#735 Check to reveal creatures when removing last object from floor tile
  src/mkobj.c
Labels: bug (minor)

#737 Lolth should wear her plate armor
  src/makemon.c
Labels: bug (minor)

#738 Add `\r` to the list of skipped characters when parsing some things
  src/files.c
Labels: enhancement

#744 Fix Malphas ritual yeeting rider corpses
  src/sounds.c
Labels: bug (minor)

#745 Fix Ahazu abductions crashing on riders
  src/spell.c
  src/xhity.c
Labels: bug (major)

#741 Fix artifacts sometimes incorrectly getting "vs vulnerable" bonus
  src/xhity.c
Labels: bug (minor)

#752 Use xname() more for beartraps
  src/hack.c
  src/trap.c
Labels: enhancement

#755 Breathless/amphibious monsters will attempt to leave water.
  src/mon.c
Labels: enhancement

#757 Glass chests shatter like other glass objects -- drop their contents.
  src/dothrow.c
  src/shk.c
Labels: bug (minor), enhancement

#759 If AD_WRAP generated from AT_HUGS fails, do not make another AT_HUGS …
  src/xhity.c
Labels: bug (major)

#763 Fix LightBlind not working
  src/vision.c
Labels: bug (minor)

#765 Add Soresu training
  src/xhity.c
Labels: bug (minor)

#768 Fix stupid
  src/mon.c
Labels: bug (minor)

#769 Fix flying monsters getting stuck on water squares
  src/monmove.c
Labels: bug (minor)

#772 Hit passthru displacement with shining weapons
  src/projectile.c
  src/xhity.c
  src/xhityhelpers.c
Labels: bug (minor)

#773 GET BACK IN THE WATER
  src/mon.c
Labels: bug (minor)

#774 Fix how non-object poison is done
  src/xhity.c
Labels: bug (minor)

#775 Priests +d(XL) damage is max once per hit
  src/artifact.c
  src/xhity.c
Labels: balance (minor), bug (minor)

#783 Numina's detection is level-wide
  src/sounds.c
Labels: bug (minor)

#776 Protect menus from malicious behaviour causing stack overflow
  src/engrave.c
  src/polyself.c
  src/spell.c
Labels: bug (minor)

#784 Add missing punctuation
  src/cmd.c
Labels: bug (minor)

#788 Chang i = (++i) to i = (i + 1)
  src/hacklib.c
Labels: bug (minor)

#789 Fix "killed the foo" livelog caused by show-hurtness
  src/do_name.c
Labels: bug (minor)

#790 Improve and fix Graz'zt's "six magics" positive effect
  src/seduce.c
Labels: bug (minor)

#791 bhitpos needs to be set before calling hit_floor2
  src/do.c
Labels: bug (major)

#787 binder spirit self-inspection
  include/extern.h
  src/cmd.c
  src/engrave.c
  src/quest.c
  src/sounds.c
Labels: enhancement

#792 Don't add extra cap to yuki-onna's str/con carry amount
  src/hack.c
Labels: bug (minor)

#793 Add separate message for thick skin resisting attacks
  src/xhity.c
Labels: bug (minor)

#794 Oops, creatures weren't correctly seeing their own square as okay
  src/mon.c
Labels: bug (minor)

#796 Tweak numbers of vorpal damage and interaction with armor
  src/artifact.c
Labels: balance (minor)

#797 Show monster DR alongside monster AC
  include/extern.h
  src/pager.c
  src/pline.c
  src/worn.c
Labels: critical enhancement

#800 Oops, the Field Marshal's Baton shouldn't count for &oUG
  include/artilist.h
Labels: bug (minor)

#805 Fix description of Antimagic Shield
  src/spell.c
Labels: bug (minor)

#814 Hedrow nobles may actually want a crowning gift
  src/pray.c
Labels: bug (minor)

#816 Consolidate all destroy_item()s into one function
  include/extern.h
  src/allmain.c
  src/artifact.c
  src/explode.c
  src/mcastu.c
  src/muse.c
  src/polyself.c
  src/potion.c
  src/pray.c
  src/trap.c
  src/xhity.c
  src/xhityhelpers.c
  src/zap.c
Labels: enhancement

#819 The Fluorite Octet can be thrown up to all 8 at once
  src/invent.c
  src/projectile.c
Labels: bug (minor)

#820 Fix typo
  dat/data.base
Labels: bug (minor)

#821 Fix buzz() printing messages for unseen mvm
  src/zap.c
Labels: bug (minor)

#839 Fix artif_hit without magr crashing
  src/xhity.c
Labels: bug (minor)

#841 Fix minor bug in faction attack changes
  src/mondata.c
Labels: bug (minor)

#843 Give the Chromatic Dragon resists her scales should grant
  src/monst.c
Labels: bug (minor)

#848 Oops, Numina wasn't granting properties AT ALL.
  src/sounds.c
Labels: bug (minor)

#851 Mjollnir grants shock res when wielded
  include/artilist.h
Labels: balance (minor)

#857 Rebalance spellbooks
  src/do_name.c
  src/objects.c
  src/spell.c
Labels: balance (minor), bug (minor), enhancement

#858 Re-add Paimon melee with spellbooks draining levels into the books
  src/artifact.c
  src/weapon.c
  src/xhity.c
Labels: bug (minor)

#861 Change menu type for describing spirit powers to fix TTY menu
  src/spell.c
Labels: bug (minor)

#862 Specify `yourinvent` is boolean
  src/pray.c
Labels: bug (minor)

#863 Old embassy of elements spirits weren't being unbound correctly
  src/sounds.c
Labels: bug (minor)

#864 Minor polyself tweaks
  src/polyself.c
  src/sounds.c
Labels: enhancement
