Repository Chris-plus-alphanumericgibberish/dNAO, pull requests merged in 2020-09, with the labels that each got.

#1057 Firing enhancements
  include/obj.h
  src/cmd.c
  src/polyself.c
  src/projectile.c
Labels: balance (minor), enhancement

#1072 Your marilith arms use your two-weapon combat skill to determine max wt
  src/xhity.c
Labels: balance (minor)

#1080 Add Dirge
  include/artifact.h
  include/artilist.h
  src/artifact.c
  src/invent.c
  src/pray.c
  src/xhity.c
  src/xhityhelpers.c
Labels: enhancement

#1083 Ludios spawns on the first possible vault
  src/mklev.c
Labels: enhancement

#1084 Correctly use polyform maxhp for artifact healing
  src/artifact.c
Labels: bug (minor)

#1085 Fix Pale Night's passive seduce
  src/xhity.c
Labels: bug (minor)

#1088 Reduce lightning-zap-induced blinding duration
  include/extern.h
  src/engrave.c
  src/zap.c
Labels: balance (minor)

#1089 Allow Marionette to be bound in the Lost Tomb
  src/sounds.c
Labels: enhancement

#1090 Vivisection traps are invalid to teleport to or generate monsters on
  src/teleport.c
Labels: bug (minor)

#1093 Add appropriate levels of Chaos2 and Chaos3 to In_outdoors()
  src/dungeon.c
Labels: bug (minor)

#1094 Fix minor BUC-related issues in pray.c
  src/pray.c
Labels: bug (minor)

#1095 Monsters shouldn't use up artifact scrolls/potions
  src/muse.c
Labels: bug (minor)

#1097 Remove "Range Restricted" wizmode warning
  src/teleport.c
Labels: enhancement

#1098 Reduce Vampire Killer's increased damage back to what was intended
  src/weapon.c
Labels: balance (minor), bug (minor)

#1100 Add waterproofing as a proper trinsic
  include/artilist.h
  include/prop.h
  include/youprop.h
  src/artifact.c
  src/cmd.c
  src/invent.c
  src/objects.c
  src/sounds.c
  src/timeout.c
  src/trap.c
  src/worn.c
Labels: enhancement

#1101 A little more misc property work
  include/prop.h
  include/you.h
  include/youprop.h
  src/apply.c
  src/eat.c
  src/fountain.c
  src/hack.c
  src/mcastu.c
  src/polyself.c
  src/potion.c
  src/pray.c
  src/seduce.c
  src/sit.c
  src/sounds.c
  src/timeout.c
  src/u_init.c
  src/worn.c
  src/xhity.c
  src/zap.c
Labels: balance (minor), enhancement

#1102 Replace is_derived_undead_mon() with appropriate permonst or specific…
  include/mondata.h
  src/display.c
  src/exper.c
  src/makemon.c
  src/mon.c
  src/mondata.c
  src/monmove.c
  src/mthrowu.c
Labels: enhancement

#1103 Monsters wearing Leo Nemaeus hides turn into Sons of Typhon.
  src/mon.c
Labels: enhancement

#1104 Grudge updates
  src/mon.c
Labels: bug (minor)

#1105 Fix dumplog maps having blank lines
  src/display.c
Labels: bug (minor)

#1106 Fix ssuffix buffer management
  src/hacklib.c
Labels: bug (minor)

#1107 Monsters with alt spellcasting show their spellcasting at end of attack chain
  src/monst.c
  src/xhity.c
Labels: enhancement

#1108 Fix findtravelpath() going back and forth
  include/flag.h
  include/you.h
  src/cmd.c
  src/hack.c
  src/options.c
Labels: bug (minor), enhancement

#1109 ucarinc is magical; applies when levitating
  src/hack.c
Labels: bug (minor)

#1110 Fix drain-pw bad seduce effect
  src/seduce.c
Labels: bug (minor)

#1111 Fix RSS-is-wisdom-implement crashing
  src/spell.c
Labels: bug (major)

#1112 Misc fossil fixes
  src/zap.c
Labels: bug (minor)

#1113 Actually truncate initmap rooms overlapped by .des maps
  include/extern.h
  src/mkmap.c
  src/sp_lev.c
Labels: bug (minor)

#1114 Don't print "Use the command #monster to speak a word of power" on polyself
  include/extern.h
  src/cmd.c
  src/polyself.c
  src/read.c
Labels: bug (minor), enhancement

#1115 Add prayer-in-progress lastprayed state
  include/you.h
  src/cmd.c
  src/pray.c
Labels: bug (minor)

#1116 Fix Incantifiers starting with maximized pw
  src/u_init.c
Labels: bug (minor)

#1117 Add wizmode killall command
  include/extern.h
  src/cmd.c
  src/read.c
Labels: enhancement

#1118 Add basic handling for keys to unshackle monsters
  include/extern.h
  src/lock.c
  src/trap.c
Labels: enhancement

#1119 Add command to unmap `I` symbols
  src/cmd.c
Labels: enhancement

#1120 Add handling for harmonium gloves's ranged accuracy penalty
  src/xhity.c
Labels: bug (minor)

#1121 Tweak armor weight-types
  include/obj.h
  include/objclass.h
  src/objects.c
Labels: balance (minor), enhancement

#1122 When given your quest, discover your quest artifact
  src/quest.c
Labels: enhancement

#1123 Don't rematerial these armors
  src/mkobj.c
Labels: bug (minor)

#1125 Replace Gae/Tulani in mklev spawns appropriately
  src/makemon.c
Labels: bug (minor)

#1126 Many more wishparser fixes
  src/objnam.c
Labels: bug (minor)

#1128 All ammo in trap should have otrap set
  src/restore.c
Labels: bug (minor)

#1129 Fix crash from attempting to turn <10 silver bullets into rockets
  src/apply.c
Labels: bug (major)

#1130 Prevent dead monsters from picking up items
  src/mon.c
Labels: bug (minor)

#1132 Fire/Frost Brand: In addition to Rakuyo, convert Rakuyo Saber and Dagger
  include/obj.h
  src/do_name.c
Labels: balance (minor)

#1133 BUFSZ wasn't long enough for some monsters
  include/global.h
  src/pager.c
Labels: bug (minor)

#1134 Add casing to wish for "gauntlets named Fire Brand"
  src/objnam.c
Labels: bug (minor)

#1135 Grappler's Grasp fixes
  src/artifact.c
  src/xhity.c
Labels: bug (minor)

#1136 Fix targeting for mass cure close and friends
  src/mcastu.c
Labels: bug (minor)

#1137 add compound option delay_length:normal|short|instant
  include/flag.h
  include/macwin.h
  include/qt_win.h
  include/winX.h
  include/wincurs.h
  include/wingem.h
  include/winprocs.h
  include/wintty.h
  src/options.c
  win/Qt/qt_win.cpp
  win/X11/winX.c
  win/curses/cursmain.c
  win/gem/wingem1.c
  win/gnome/gnbind.c
  win/gnome/gnbind.h
  win/tty/termcap.c
  win/win32/mswproc.c
  win/win32/winMS.h
Labels: enhancement

#1139 Change Disint Ray to be a zap-type spell, not an invisible beam.
  src/mcastu.c
  src/zap.c
Labels: enhancement

#1140 Polyself fixes
  src/monst.c
  src/polyself.c
Labels: bug (minor)

#1141 Fix glass/rock rocks generated by polymorph
  src/zap.c
Labels: bug (minor)

#1091 Change artilist from a header to a source
  GNUmakefile
  include/artifact.h
  src/allmain.c
  src/artifact.c
  src/artilist.c
  src/do_name.c
  src/invent.c
  src/objnam.c
  src/pray.c
  src/quest.c
  src/weapon.c
  src/wield.c
  src/xhity.c
  util/lev_main.c
  util/makedefs.c
Labels: enhancement

#1143 Major Macromagic Improvements
  include/macromagic.h
  src/artilist.c
  src/objects.c
Labels: critical enhancement

#1147 Drastically change how mextra works on backend
  GNUmakefile
  include/edog.h
  include/emin.h
  include/epri.h
  include/eshk.h
  include/exstruct.h
  include/extern.h
  include/horrordata.h
  include/mextra.h
  include/monst.h
  include/permonst.h
  include/vault.h
  src/allmain.c
  src/apply.c
  src/artifact.c
  src/cmd.c
  src/dig.c
  src/do.c
  src/do_name.c
  src/dog.c
  src/dogmove.c
  src/dokick.c
  src/dothrow.c
  src/eat.c
  src/end.c
  src/makemon.c
  src/mextra.c
  src/minion.c
  src/mkobj.c
  src/mon.c
  src/mondata.c
  src/monmove.c
  src/monst.c
  src/mplayer.c
  src/muse.c
  src/music.c
  src/pager.c
  src/pline.c
  src/pray.c
  src/priest.c
  src/read.c
  src/restore.c
  src/save.c
  src/seduce.c
  src/shk.c
  src/shknam.c
  src/sounds.c
  src/steed.c
  src/timeout.c
  src/trap.c
  src/u_init.c
  src/vault.c
  src/wizard.c
  src/xhity.c
  src/xhityhelpers.c
  src/zap.c
Labels: enhancement (complex)

#1149 Fix limited moon bugs
  src/artifact.c
Labels: bug (minor)

#1151 Double size of nulls buffer
  src/save.c
Labels: bug (minor)

#1152 Move global curses declarations from .h to .c
  include/wincurs.h
  win/curses/cursinit.c
Labels: bug (minor)

#1153 Correctly check len before checking string
  src/objnam.c
Labels: bug (minor)

#1156 Fix picking special rooms
  src/mklev.c
Labels: bug (minor)

#1157 Check isok() for occupied()
  src/mklev.c
Labels: bug (minor)

#1160 Check eggs have mtyp before indexing mons[]
  src/dog.c
  src/muse.c
  src/weapon.c
Labels: bug (minor)

#1161 Always keep mvar_vector >=0
  src/allmain.c
  src/mon.c
Labels: bug (minor)

#1162 Being gifted Hellrider's Saddle unrestricts riding
  src/pray.c
Labels: enhancement

#1164 Fix and clean self-inspect "soul is bound to" message backend
  src/cmd.c
Labels: bug (minor)

#1166 Else-if eating tins to avoid checking otmp after freeing it
  src/eat.c
Labels: bug (minor)

#1169 Destroy nhwin after #ability early return
  src/cmd.c
Labels: bug (major)

#1170 Catch out of bounds array read
  src/invent.c
Labels: bug (major)

#1171 Only warn for artifact eyeballs/hands
  src/eat.c
Labels: bug (minor), enhancement

#1174 Correct another BAD EGG
  src/xhity.c
Labels: bug (minor)

#1175 Check strlen before using left offset
  src/options.c
Labels: bug (minor)

#1176 Guard against OOB in mon_in_room
  src/sounds.c
Labels: bug (minor)

#1177 Prevent overflow in setting directions at start
  src/cmd.c
Labels: bug (minor)

#1178 Zero initialise special rooms
  src/mklev.c
Labels: bug (major)

#1179 Deprecate "wepgone". Send (struct obj **)(&weapon).
  include/extern.h
  src/allmain.c
  src/apply.c
  src/artifact.c
  src/ball.c
  src/do.c
  src/do_wear.c
  src/dokick.c
  src/explode.c
  src/mcastu.c
  src/mkobj.c
  src/pickup.c
  src/projectile.c
  src/spell.c
  src/trap.c
  src/worm.c
  src/xhity.c
Labels: bug (minor), enhancement

#1180 Fix ls bug
  src/mon.c
Labels: bug (major)

#1187 Stationary engulfers stay in place
  src/xhity.c
  src/xhityhelpers.c
Labels: bug (minor)

#1193 Newsym pets to give them the correct highlight immediately
  src/dog.c
Labels: enhancement

#1195 Fix drowning issues
  src/end.c
  src/teleport.c
  src/timeout.c
  src/trap.c
Labels: bug (major), enhancement

#1182 Attach lightsources directly to mons/objs
  include/extern.h
  include/lev.h
  include/monst.h
  include/obj.h
  src/light.c
  src/makemon.c
  src/mkobj.c
  src/mon.c
  src/polyself.c
  src/restore.c
  src/save.c
  src/timeout.c
  src/were.c
Labels: enhancement (complex)

#1198 Sickles are throwing weapons
  include/obj.h
  include/xhity.h
Labels: bug (minor)

#1199 Player trains Juyo skill by attacking disadvantaged targets
  src/xhity.c
Labels: bug (minor)

#1200 Modify Chris's new monsters to fit new monst.c format
  src/monst.c
Labels: bug (major)

#1201 Merge adding AD_SSEX passive and wepgone-deprecation
  src/xhity.c
Labels: bug (minor)

#1202 Check that magr exists for sneak attacking
  src/xhity.c
Labels: bug (major)

#1194 Tweak wishing for rematerialed objects
  include/extern.h
  src/mkobj.c
  src/objnam.c
Labels: enhancement

#1190 Add new artifact: Bloodletter
  include/artifact.h
  include/extern.h
  src/apply.c
  src/artifact.c
  src/artilist.c
  src/explode.c
  src/invent.c
  src/objnam.c
  src/weapon.c
Labels: enhancement

#1203 Clean up warnings
  include/obj.h
  src/light.c
  src/mextra.c
  src/monmove.c
  src/oextra.c
  src/polyself.c
  src/read.c
Labels: enhancement

#1205 Fix mdofire() and let monsters offhand guns/blasters
  src/projectile.c
  src/weapon.c
Labels: bug (minor)

#1207 Enhanced disintegration can be reflected normally
  src/projectile.c
Labels: bug (minor)
