Repository Chris-plus-alphanumericgibberish/dNAO, pull requests merged in 2020-08, with the labels that each got.

#1019 Oops, set uhurtm
  src/xhity.c
Labels: bug (minor)

#1020 Fix `killer` for death-to-exploding-wand
  src/xhityhelpers.c
Labels: bug (minor)

#1023 De-kludge "eternal" lightsources & engulfers interaction
  src/invent.c
  src/light.c
  src/mkobj.c
  src/o_init.c
  src/steal.c
Labels: bug (minor), enhancement

#1021 Reading slabs/tiles breaks illiterate conduct
  src/read.c
Labels: bug (minor)

#1022 Replace some oc_oprop checks with item_has_property
  src/artifact.c
  src/mcastu.c
  src/mkobj.c
  src/muse.c
  src/zap.c
Labels: bug (minor)

#1024 Add terminators to Halfdragon Noble deity minion lists
  src/role.c
Labels: bug (minor)

#1026 Some artifacts now cancel on 10% of hits!
  include/artifact.h
  include/artilist.h
  src/artifact.c
Labels: balance (minor)

#1027 Greatly decrease the to-hit penalty for using overweight offhand weapons
  include/extern.h
  src/weapon.c
  src/xhity.c
Labels: balance (major)

#1028 Use a separate list of buffers when displaying your inventory
  include/flag.h
  src/invent.c
  src/objnam.c
Labels: bug (minor)

#1029 things miss *you*, not *it*
  src/zap.c
Labels: bug (minor)

#1030 All (unpolyd) players can twoweapon
  src/weapon.c
  src/wield.c
Labels: balance (major)

#1031 Sunbeam/Moonbeam return to your inventory some time after being fired
  include/artilist.h
  include/extern.h
  include/timeout.h
  src/o_init.c
  src/projectile.c
  src/timeout.c
Labels: balance (minor), enhancement

#1032 Fix making a dragonshield with a twohanded weapon (or 2 weapons)
  src/read.c
Labels: bug (minor)

#1033 Fix hang on init
  src/o_init.c
Labels: bug (major)

#1035 Fix wildmisses being overly verbose and some not taking actions
  src/xhity.c
Labels: bug (minor)

#1036 Rewrite a bunch of glyph/thought handling
  GNUmakefile
  include/extern.h
  include/hack.h
  include/prop.h
  include/thoughtglyph.h
  include/you.h
  include/youprop.h
  src/apply.c
  src/attrib.c
  src/bones.c
  src/cmd.c
  src/read.c
  src/sounds.c
  src/thoughtglyph.c
Labels: enhancement

#1037 Don't make sneak attacks on oneself
  src/xhity.c
Labels: bug (minor)

#1038 Don't lock the player into choosing a lock to open
  src/lock.c
Labels: enhancement

#1040 Fix Stormbringer over-messaging on XL0-drain-kill
  src/artifact.c
Labels: bug (minor)

#1041 Function to find all items
  include/extern.h
  include/obj.h
  src/artifact.c
  src/hack.c
  src/zap.c
Labels: enhancement

#1025 Grandmaster's robe isn't a good first gift
  include/artilist.h
Labels: balance (minor)

#1047 Fix naming of cheap plastic imitation of the amulet of yendor
  src/objnam.c
Labels: bug (minor)

#1048 Minor horror improvements
  include/ehor.h
  src/mondata.c
Labels: enhancement

#1049 HOW DID I MISS THIS
  src/mkobj.c
Labels: bug (minor)

#1050 Shatterproof glass/obsidian prying objects should be effective
  src/lock.c
Labels: bug (minor)

#1051 Blaster ammo inherits some things
  src/projectile.c
Labels: balance (minor), bug (minor)

#1053 Martial aid weapons do NOT stack with gloves / other unarmed boosters
  include/xhity.h
  src/xhity.c
Labels: balance (minor)

#1054 ifdef STEED, and only player gets to ride their steed for polearm use
  src/xhity.c
Labels: bug (minor)

#1055 Allow wishing for figurines of uniqs/nowish monsters
  src/dog.c
  src/objnam.c
Labels: enhancement

#1056 Remove Blind vision optimization to accomodate LightBlind+Xray
  src/hack.c
  src/vision.c
Labels: bug (minor)

#1058 Fix unique statue objnam
  src/objnam.c
Labels: bug (minor)

#1060 Give Marionette back axe skill
  src/sounds.c
Labels: bug (minor)

#1061 Scrolls of ward use `long oward` to store the *floorID* for some reason
  src/objnam.c
Labels: bug (minor)

#1062 Nerf Jester's Mirth duration
  src/spell.c
Labels: balance (minor)

#1065 Fix magr/mdef confusion in AD_BARB passive message
  src/xhity.c
Labels: bug (minor)
