Repository Chris-plus-alphanumericgibberish/dNAO, pull requests merged in 2021-06, with the labels that each got.

#1548 Hide "You have 0 parasite eggs" enlightenment message
  src/cmd.c
Labels: enhancement

#1549 Un-blind dinosaurs
  src/monst.c
Labels: bug (minor)

#1551 You cannot load armed grenades into the mass-shadow pistol
  src/pickup.c
Labels: bug (major)

#1553 Null-check cobj for mass shadow pistols
  include/obj.h
  src/projectile.c
Labels: bug (minor)

#1555 De-silver Death-Spear of Keptolo
  src/artilist.c
Labels: bug (minor)

#1556 Fix infinite loop in dungeon of ill regard generation
  src/mkmaze.c
Labels: bug (major)

#1557 Fix allitems function not working for >1 monster inventories on level
  src/hack.c
Labels: bug (major)

#1558 Polearm menu shouldn't show extra info to player
  src/apply.c
Labels: bug (minor)

#1560 Add quick check-and-abort to priest_talk() if mon isn't a real priest
  src/priest.c
Labels: bug (major)

#1561 Fix typo
  include/thoughtglyph.h
Labels: bug (minor)

#1562 Use untame() to detame bones' pets.
  src/bones.c
Labels: bug (minor)

#1563 mfind_target() should exclude dead monsters
  src/mthrowu.c
Labels: bug (minor)

#1566 Prevent "bless wielded item" from modifying spe of non-weapons
  src/sounds.c
Labels: balance (major)

#1568 Fix logic in choosing item to goatbless
  src/pray.c
Labels: bug (minor)

#1569 Fix x/y asymmetry in small-radius darksources
  src/light.c
Labels: bug (minor)

#1565 Modfiy DEADMONSTER() macro to claim player is alive, not dead.
  include/monst.h
  src/artifact.c
  src/do_wear.c
  src/mcastu.c
  src/xhity.c
Labels: enhancement

#1574 Anti summon abuse
  src/muse.c
  src/potion.c
  src/spell.c
Labels: balance (minor)

#1575 Fix some giveaways in farlook
  src/pager.c
Labels: bug (minor)

#1576 Minor bugfixes and commenting
  src/dog.c
  src/makemon.c
  src/mon.c
  src/mondata.c
Labels: bug (minor)

#1578 Fix summons with *random* artifacts causing them to exist
  src/artifact.c
Labels: bug (minor)

#1579 Only rust deep(er) ones' gear, not other erosions.
  src/makemon.c
Labels: bug (minor)

#1582 Fix "Fire Pillar" not respecting inventory fire resistance
  src/mcastu.c
Labels: bug (minor)

#1583 Uniques summoned via demongating (etc) are not marked as summons in a…
  src/minion.c
Labels: balance (minor)

#1584 Fix shades being hit by any projectile
  include/extern.h
  src/projectile.c
  src/xhity.c
  src/xhityhelpers.c
Labels: bug (minor)

#1585 Misc eating fixes
  src/eat.c
Labels: bug (minor)

#1586 Fix mazes sometimes crashing on generation
  src/mkmap.c
  src/mkmaze.c
Labels: bug (major)

#1587 Fix bad logic leaving hawaiian shorts as the only protection vs bisection
  src/artifact.c
Labels: bug (minor)
