Repository Chris-plus-alphanumericgibberish/dNAO, pull requests merged in 2021-01, with the labels that each got.

#1372 Fixes for xcasty with bad target
  src/mcastu.c
Labels: bug (minor)

#1374 Fix gremlin cloning
  src/makemon.c
  src/mextra.c
Labels: bug (minor)

#1375 Fix "foo's helmet blocks your attack to their head" msg
  src/xhity.c
Labels: bug (minor)

#1377 Close lockfile properly
  src/files.c
Labels: bug (major)

#1378 Fix backwards "while-carried" artifact logic
  src/artifact.c
Labels: bug (minor)

#1381 Safer clone_mon()
  src/makemon.c
Labels: bug (minor)

#1382 Nerf knockback artifacts
  src/artifact.c
Labels: balance (major)

#1383 Nerf Argentum golems' ranged damage
  src/monst.c
Labels: balance (minor)

#1384 Rework Oracle, adding enlightenment and dungeon inclusion hints
  src/rumors.c
Labels: enhancement

#1386 Nerf Octetsabers
  src/weapon.c
Labels: balance (minor)

#1387 Actually use listed artifact weights
  include/artifact.h
  include/extern.h
  src/artifact.c
  src/artilist.c
  src/mkobj.c
Labels: enhancement

#1389 Slap a bandaid on monster mextra restore
  src/restore.c
Labels: bug (major)

#1391 Increase maxweight for player sizes above medium
  src/weapon.c
Labels: balance (minor)

#1392 Be extra-careful with restarting the monmoving loop
  src/mon.c
Labels: bug (major)

#1396 Fix statues of PName monsters
  src/objnam.c
Labels: bug (minor)

#1397 Fix naming of Angel minions
  src/priest.c
Labels: bug (major)

#1398 Wrong mon pointer
  src/mcastu.c
Labels: bug (major)

#1399 Handle newcham() making horrors
  src/mon.c
Labels: bug (major)

#1400 Fix Arsenal's volley
  src/projectile.c
Labels: bug (minor)

#1401 Use same check between an() and xname() for using a/an.
  src/objnam.c
Labels: bug (minor)

#1402 Allow reading of anti-clockwise metamorphosis glyphs
  src/read.c
Labels: bug (minor)

#1403 Zombies should be generated hostile
  src/makemon.c
Labels: bug (minor)

#1405 Allow hypospray to be used via item menu
  src/invent.c
Labels: bug (minor)

#1406 Fix memcpy for oextra
  src/oextra.c
Labels: bug (major)

#1407 Move (m/o)extra tables into their .c files (from .h)
  include/mextra.h
  include/oextra.h
  src/mextra.c
  src/oextra.c
Labels: enhancement

#1408 Prevent extinction of monsters from #wizmakemap
  src/cmd.c
Labels: bug (minor)

#1409 Use anonymous unions where appropriate instead of #define
  include/obj.h
  include/trap.h
Labels: enhancement

#1413 Change timer backend
  include/extern.h
  include/monst.h
  include/obj.h
  include/timeout.h
  src/apply.c
  src/dig.c
  src/eat.c
  src/invent.c
  src/mkobj.c
  src/mon.c
  src/mthrowu.c
  src/objnam.c
  src/pickup.c
  src/restore.c
  src/save.c
  src/shk.c
  src/sp_lev.c
  src/timeout.c
  src/topten.c
  src/xhity.c
Labels: enhancement (complex)

#1416 Only train twoweapon combat in melee
  src/xhity.c
Labels: bug (minor)

#1420 Fix zap-sleep-resist message
  src/zap.c
Labels: bug (minor)

#1422 Binder msg fixes
  src/artifact.c
  src/sounds.c
Labels: bug (minor)

#1421 Elemental-damage artifacts should check InvResists before destroying …
  src/artifact.c
Labels: bug (minor)

#1423 Fix panic() on helm of undeath lifesaving w/ size change
  src/end.c
Labels: bug (major)

#1424 Small mcastu changes
  src/mcastu.c
Labels: balance (minor), bug (minor)

#1434 Correctly handle alignment and hostility of autons after killing Axus
  src/makemon.c
  src/mon.c
Labels: bug (minor)

#1435 Lava doesn't destroy artifact boots
  src/trap.c
Labels: balance (minor)

#1436 Scroll of Consecration changes
  src/read.c
Labels: balance (minor)

#1437 Only player's vampire bites feed you >_>
  src/xhity.c
Labels: bug (minor)

#1438 Monsters can only summon a demon/devil if they've found you
  src/mcastu.c
Labels: bug (minor)

#1439 Oops
  src/trap.c
Labels: bug (major)

#1415 Port the ability to #name f
  include/extern.h
  src/cmd.c
  src/do_name.c
  src/pager.c
Labels: enhancement

#1441 Summon timer fixes
  src/timeout.c
Labels: bug (major)

#1442 The Master Key of Thievery is supposed to grant warning
  src/artilist.c
Labels: bug (minor)

#1443 Fix double percent in description of Naen and Krau.
  src/invent.c
Labels: bug (minor)

#1444 Fix copying size
  src/mextra.c
  src/oextra.c
Labels: bug (major)

#1445 Apparently we had monsters with ispriest or isminion flag and no mx
  src/do_name.c
  src/priest.c
Labels: bug (major)

#1447 Desummon_obj needs to handle obj->ocarry's weapon pointers.
  src/timeout.c
Labels: bug (major)

#1448 Fix divide-by-zero possibility
  src/botl.c
Labels: bug (major)

#1451 Gold is always mergable.
  src/invent.c
Labels: bug (minor)

#1452 Fix crash on using stethoscope on summoned angels.
  src/pline.c
Labels: bug (major)

#1454 Shush warnings
  src/invent.c
  src/mextra.c
  src/objnam.c
  src/oextra.c
  src/xhity.c
Labels: bug (major), bug (minor)

#1455 Update symbols of angered quest guardians when you attack Q leader
  src/mon.c
Labels: bug (minor)

#1456 Prevent shadowsteel equipment from showing "shade" encyc entry
  dat/data.base
Labels: bug (minor)

#1457 Crowning gifts are gifted
  src/crown.c
Labels: bug (minor)

#1458 Add dNetHack version to dumplog
  src/end.c
Labels: enhancement

#1459 Artifact mummy wrappings aren't destroyed when breaking Shiro's taboo
  src/allmain.c
Labels: bug (minor)

#1460 Recalculate vision on setworn()
  src/worn.c
Labels: bug (minor)

#1461 Change message for multiple poisons being resisted
  src/xhity.c
Labels: bug (minor)

#1462 Androids need subethaic components, you need the right kind of compon…
  src/apply.c
Labels: balance (minor), bug (minor)

#1463 Change foocubi winding sedu effect
  src/seduce.c
Labels: bug (minor)

#1464 Fix poison spray tombstone message
  src/zap.c
Labels: bug (minor)

#1465 This should interrupt wearing armor.
  src/do_wear.c
Labels: bug (minor)
