Repository Chris-plus-alphanumericgibberish/dNAO, pull requests merged in 2021-09, with the labels that each got.

#1709 Fix Creature in the Ice
  src/dig.c
Labels: bug (major)

#1699 Add clockwork hunger words to curses statusline
  win/curses/cursstat.c
Labels: bug (minor)

#1700 Add a blanket test asking for "2 <objs>"
  src/testing.c
Labels: enhancement

#1701 Allow accessing pokedex by monster name via `?`
  src/pager.c
Labels: enhancement

#1703 Change message of [extra] healing if you can see hurtness
  include/extern.h
  include/mondata.h
  src/do_name.c
  src/zap.c
Labels: enhancement

#1706 Fix disintegration blasts unblocking vision on undug tiles
  src/zap.c
Labels: bug (minor)

#1708 Change spell-quiver key from `@` to `&`
  src/spell.c
Labels: bug (minor)

#1710 Fix drow's carried lightsources going out when in pits
  src/vision.c
Labels: bug (minor)

#1711 Fix crash if monster nonlethally attacks steed forcing dismount
  src/xhity.c
Labels: bug (major)

#1712 Remove old breathwep function, use flash_type
  src/mthrowu.c
  src/projectile.c
Labels: bug (minor)

#1714 Fix Mammon's armor
  src/makemon.c
Labels: bug (minor)

#1718 Check that mplayers have names before reading them.
  src/mon.c
Labels: bug (major)

#1725 Adjust Oracle dungeon hints
  src/rumors.c
Labels: balance (minor)

#1719 Numina doesn't grant Omnisense
  src/sounds.c
Labels: bug (minor)

#1722 `rnd_misc_item()` was missed during the anti-summon-items change
  src/muse.c
Labels: balance (minor)

#1727 Zero `fakemon`
  src/pager.c
Labels: bug (major)

#1729 Fix Juyo training
  src/xhity.c
Labels: bug (minor)

#1731 Buff Lightning Storm's accuracy
  src/spell.c
Labels: balance (minor)

#1735 Don't outright say what the tohit penalty is
  src/weapon.c
Labels: bug (minor)

#1736 Check `youagr` before selling thrown projectiles
  src/projectile.c
Labels: bug (minor)

#1737 Fix cursed wage of greed targeting
  src/apply.c
Labels: bug (minor)

#1747 Monsters cannot gate on a wild miss
  src/xhity.c
Labels: bug (minor)

#1748 Mirrored Mask buffs
  src/artifact.c
Labels: balance (minor)

#1751 Fix Staff of Necromancy invoke
  src/artifact.c
  src/invent.c
Labels: bug (minor)

#1754 Fix crash on wizard harassment
  src/minion.c
Labels: bug (major)

#1755 Use proper verb tense for "mind is" vs "senses are"
  src/seduce.c
Labels: bug (minor)

#1756 Fix re-carving artifacts being able to destroy them
  src/apply.c
Labels: bug (minor)

#1757 Fix must-wield check on Keptolo's invoke, remove unnecessary `isok()`
  src/artifact.c
Labels: bug (minor)

#1758 Fix uvm xdamagey() not disintegrating corpses when appropriate
  src/xhity.c
Labels: bug (minor)

#1759 Remove unnecessary "the"
  src/xhityhelpers.c
Labels: bug (minor)

#1764 Fix Rod of Force inspect skill
  src/weapon.c
Labels: bug (major)
