Repository Chris-plus-alphanumericgibberish/dNAO, pull requests merged in 2021-05, with the labels that each got.

#1499 Prevent Ahazu from abducting quest nemeses and making the quest impos…
  src/spell.c
  src/xhity.c
Labels: bug (major)

#1489 Fix looted artifacts being remembered by gods not in your game
  src/bones.c
Labels: bug (minor)

#1491 Allow deliberate polyself into own race to force newman()
  src/polyself.c
Labels: bug (minor)

#1492 Fix off-by-one error when identifying randomly-generated maze rooms
  src/mkmaze.c
  src/sp_lev.c
Labels: bug (minor)

#1493 Monsters shouldn't attempt to target >8 squares away
  src/mthrowu.c
Labels: bug (minor)

#1494 Add "Slimify" monster spell
  include/monflag.h
  src/mcastu.c
  src/xhity.c
Labels: enhancement

#1495 Make demon-gating a #monster ability for players
  include/extern.h
  include/mondata.h
  src/cmd.c
  src/polyself.c
  src/xhity.c
  src/xhityhelpers.c
Labels: balance (minor)

#1503 Fix Spellbooks of Secrets double-artifacting
  src/mkobj.c
Labels: bug (minor)

#1504 Use revive() as the base of vampiric-minion-raising
  src/polyself.c
Labels: bug (minor)

#1508 Check vis before printing armor-destruction messages from flaying wea…
  src/artifact.c
Labels: bug (minor)

#1511 Fix rcfile traps option reading incorrect number of traps
  include/rm.h
Labels: bug (minor)

#1512 Pet vampires recognize potions of blood as food
  include/obj.h
  src/dog.c
  src/dogmove.c
Labels: bug (minor)

#1514 Always check summoner_gone()
  src/dog.c
Labels: bug (major)

#1515 Fix all_items function not working for >1 monster inventory per level.
  src/hack.c
Labels: bug (major)

#1517 Check otmp exists before poisoning it
  src/makemon.c
Labels: bug (minor)

#1516 Move chiropteran group-spawning code to be reachable
  src/makemon.c
Labels: bug (minor)

#1518 Prevent artifact weapons from being set to shell
  src/shknam.c
Labels: bug (minor)

#1519 Fix impossibles from wishing for partly eaten/drained foodstuffs
  include/extern.h
  src/eat.c
  src/objnam.c
Labels: balance (minor), bug (minor)

#1520 Don't panic() when failing to relink summons to their summoner
  src/mextra.c
  src/oextra.c
Labels: bug (major)

#1522 Minor poison halfdragon buffs
  include/extern.h
  include/obj.h
  include/zap.h
  src/mondata.c
  src/projectile.c
  src/region.c
  src/xhity.c
  src/xhityhelpers.c
  src/zap.c
Labels: balance (minor)

#1523 Up the weight of a Chiropteran's starting heavy iron ball to 1600
  src/allmain.c
Labels: balance (minor)

#1524 Gremlins get instakilled by the First Word
  src/spell.c
Labels: balance (minor)

#1525 Fix stealing from outside shop with grappling hook
  include/extern.h
  src/pickup.c
  src/shk.c
Labels: bug (minor)

#1527 Fix unclear parens
  src/allmain.c
Labels: bug (minor)

#1528 Make summons' inventories travel with them
  include/extern.h
  src/dog.c
  src/mon.c
  src/timeout.c
Labels: bug (minor)

#1529 "Worldshaper" Mahadevae on the plane of earth
  include/extern.h
  include/monst.h
  src/dig.c
  src/makemon.c
  src/mondata.c
  src/monmove.c
  src/read.c
Labels: balance (minor)

#1538 Delusion-monsters maintain their misappearance outside of LoS.
  src/display.c
Labels: bug (minor)

#1539 Fix having multiple timers on something
  src/timeout.c
Labels: bug (major)

#1540 Fix hallucination not obscuring monster symbols
  include/display.h
  src/display.c
  src/worm.c
Labels: bug (minor)

#1541 Split timers when cloning monsters
  include/extern.h
  src/makemon.c
  src/mkobj.c
  src/timeout.c
Labels: bug (major)

#1542 Don't desummon in-use objects causing double delete
  src/timeout.c
Labels: bug (major)

#1544 Pets cannot catch your punishment-ball
  src/projectile.c
Labels: bug (major)

#1545 Fix a number of Clang warnings
  src/apply.c
  src/artifact.c
  src/invent.c
  src/mkobj.c
  src/mon.c
  src/pray.c
  src/seduce.c
  src/shk.c
  src/wizard.c
  src/xhity.c
  src/zap.c
Labels: bug (minor)

#1546 Add a couple safeguards to timers
  src/timeout.c
Labels: bug (minor)

#1547 Fix polearm relative-aiming letter incrementation
  src/apply.c
Labels: bug (minor)
