Repository Chris-plus-alphanumericgibberish/dNAO, pull requests merged in 2021-02, with the labels that each got.

#1467 Undo shush-warning to fix wishes
  src/objnam.c
Labels: bug (major)

#1468 Fix doll of binding segfaults
  src/spell.c
Labels: bug (major)

#1469 Slave to Armok does extra damage to MG_PRINCE, not just MG_LORD
  src/artilist.c
  src/invent.c
Labels: balance (minor)

#1471 Use correct string function
  src/xhity.c
Labels: bug (minor)

#1472 Stethoscopes show mberserk status effect
  src/pline.c
Labels: enhancement

#1473 Fix monsters thinking they could shoot through you
  src/projectile.c
Labels: bug (minor)

#1474 Reduce copy-paste of non-poison-drain-stat attacks in xhity.
  src/xhity.c
Labels: enhancement

#1475 Be stricter on when to be safe making melee attacks
  src/xhity.c
Labels: balance (minor)

#1477 The player is supposed to get their polyform's dodgeAC
  src/do_wear.c
Labels: bug (minor)

#1479 Fix singing sword songs (life, fear, courage)
  src/artifact.c
  src/xhity.c
Labels: bug (minor)
