Repository Chris-plus-alphanumericgibberish/dNAO, pull requests merged in 2022-01, with the labels that each got.

#1826 Fix starlight diluting into (other things) and staying lit, again
  src/trap.c
Labels: bug (minor)

#1827 Fix sunless sea 3 panicking if `;` are extinct/genocided
  dat/sunlesssea.des
Labels: bug (major)

#1828 Wizlevelport menu, take two.
  include/extern.h
  include/flag.h
  include/you.h
  src/cmd.c
  src/dungeon.c
  src/mklev.c
  src/options.c
  src/teleport.c
Labels: enhancement

#1829 No more dmonsfree errors
  include/monst.h
  src/mon.c
Labels: enhancement

#1825 Don't make doors in not okay places
  src/mklev.c
Labels: bug (minor)

#1830 `all_items()` should use its sanity-checking `in_progress` bool
  src/hack.c
Labels: bug (minor)

#1831 All sickles are throwing weapons
  include/obj.h
  src/projectile.c
  src/weapon.c
Labels: balance (minor)

#1832 Generally, projectiles hurt -- only thrown arrows/bolts/bullets suck.
  include/hack.h
  src/apply.c
  src/artifact.c
  src/ball.c
  src/do.c
  src/dokick.c
  src/explode.c
  src/mcastu.c
  src/muse.c
  src/projectile.c
  src/spell.c
  src/trap.c
  src/xhity.c
Labels: balance (minor)

#1833 Kludge Medusa's gaze some more
  src/xhity.c
Labels: bug (minor)

#1840 Don't `impossible()` on failing to find a light/timer in processing c…
  src/light.c
  src/timeout.c
Labels: bug (minor)

#1842 Hod steal your weapon, and can break it
  include/extern.h
  src/shk.c
  src/xhity.c
Labels: bug (major)

#1844 Make `e` passive paralysis use xgazey
  src/xhity.c
Labels: bug (minor)

#1846 Patch no rot lichen
  include/extern.h
  src/makemon.c
  src/mkobj.c
  src/pickup.c
  src/sp_lev.c
  src/timeout.c
Labels: bug (minor)

#1848 Fix off-by-one in plumach village left-right rooms
  src/mkroom.c
Labels: bug (minor)

#1849 Check `priest` exists before modifying it
  src/pray.c
Labels: bug (minor)

#1852 Improve wording of returning ammo
  src/projectile.c
Labels: enhancement

#1853 Add an isok() to wake_nearto
  src/mon.c
Labels: enhancement

#1854 Fix Houchou after changing fired/misthrown hmoncodes
  src/projectile.c
  src/xhity.c
Labels: bug (minor)

#1855 If a creature doesn't naturally have an engulf, can't keep player eng…
  src/xhity.c
Labels: bug (minor)

#1857 Skip des coordinate sanity checks
  dat/Android.des
  dat/Binder.des
  dat/Caveman.des
  dat/Madman.des
  dat/Moria.des
  dat/Pirate.des
  dat/chaos.des
  dat/chaos2.des
  dat/gehennom.des
  dat/neutrality.des
  util/lev_comp.l
  util/lev_comp.y
Labels: enhancement

#1858 Don't re-aim when defender moves
  src/xhity.c
Labels: bug (minor)

#1861 Rehack circlet desc on restore
  include/extern.h
  src/allmain.c
  src/o_init.c
Labels: bug (minor)

#1863 Fix projectile reflection possible infinite loops
  include/monattk.h
  src/projectile.c
Labels: bug (minor)

#1864 Look up artifacts in-game with `/n`
  include/extern.h
  src/artifact.c
  src/do_name.c
  src/invent.c
  src/objnam.c
  src/pager.c
Labels: enhancement

#1865 Fix more places where untame() should be being called
  src/allmain.c
  src/dogmove.c
  src/mon.c
Labels: bug (minor)

#1866 Put dragons' tailslaps in their statblock.
  src/allmain.c
  src/monst.c
  src/xhity.c
Labels: enhancement
