Repository Chris-plus-alphanumericgibberish/dNAO, pull requests merged in 2022-03, with the labels that each got.

#1874 Fix mplayer, horror template names
  include/extern.h
  src/do_name.c
  src/end.c
  src/mondata.c
  src/pager.c
Labels: bug (minor)

#1878 Fix mass shadow pistol, fluorite octet
  src/projectile.c
Labels: bug (minor)

#1879 Shopkeepers shouldn't buy summoned items
  src/shk.c
Labels: bug (minor)

#1881 Update the lighting of the /resized/ room, duh
  src/mklev.c
Labels: bug (minor)

#1886 Fix weapon skill, inspect for Wand of Orcus
  src/invent.c
  src/weapon.c
Labels: bug (minor)

#1893 Expand `deadmonster` to 2 bits to mark 'dead' as well as 'purge'.
  include/monst.h
  src/mon.c
  src/worn.c
Labels: bug (minor)

#1895 Oops, re-add fix_object() adding missing lightsources to eternal lights
  src/o_init.c
Labels: bug (minor)

#1894 Split randpoly-specific behaviour into its own function
  include/extern.h
  src/artifact.c
  src/potion.c
  src/zap.c
Labels: enhancement

#1898 Dead trees in undiggable regions are also no-dig
  src/hack.c
Labels: bug (minor)

#1904 Check for `hp<1` monsters in `dmonsfree()`
  src/mon.c
Labels: bug (minor)

#1899 Handle focusing gem disappearing from lightsabers
  include/extern.h
  src/apply.c
  src/mkobj.c
Labels: bug (major)

#1900 Bandaid armor disappearing mid don/doff
  src/shk.c
  src/worn.c
Labels: bug (major)

#1908 Fix sanityflag variant of monster parser
  util/lev_comp.y
Labels: bug (minor)

#1902 Fix errant `break`, should be `return`
  src/xhity.c
Labels: bug (minor)
