Repository Chris-plus-alphanumericgibberish/dNAO, pull requests merged in 2023-01, with the labels that each got.

#2045 Make more levels bones eligible!
  dat/dngnch1.def
  dat/dngnch2.def
  dat/dngnch3.def
  include/extern.h
  src/bones.c
  src/dungeon.c
  src/files.c
  src/restore.c
Labels: enhancement

#2049 Fix physical breath attacks
  src/projectile.c
  src/zap.c
Labels: bug (minor)

#2050 Fix Pokedex readout for monsters with 0 race
  src/pager.c
Labels: bug (minor)

#2063 Items "confers magical breathing", not "makes you magical breathing"
  src/invent.c
Labels: bug (minor)

#2069 Make Priest quest fill slightly more interesting!
  dat/Priest.des
  src/sp_lev.c
  util/lev_comp.y
Labels: enhancement

#2070 Show "eroded" erosion word for damaged non-damagable items.
  src/objnam.c
Labels: bug (minor)

#2071 Fix capitalization of "the Black Mother" when being rejected from her…
  src/pray.c
Labels: bug (minor)

#2073 Silently release held enemies when trying to go up/down stairs
  src/do.c
Labels: bug (minor)

#2084 Fix [Gatetown] printing everywhere in ctrl-o
  src/dungeon.c
Labels: bug (minor)

#2085 Missing `NON_PM` in default minion list #defines
  include/godlist.h
Labels: bug (minor)

#2086 Fix crash on teleporting Rider corpses that like items
  include/extern.h
  include/timeout.h
  src/do.c
  src/timeout.c
Labels: bug (major)

#2088 Shopkeepers must follow is_poisonable() rules
  src/shk.c
Labels: bug (minor)

#2089 Always check if spell would be useless before mcasting
  src/mcastu.c
Labels: bug (minor)

#2090 Merging/freeing fired ammo affects multishot
  include/decl.h
  include/extern.h
  src/projectile.c
  src/shk.c
Labels: bug (major)

#2091 Fix wizard harassment msummon crash
  src/minion.c
Labels: bug (major)

#2092 Throne Rooms cannot place cells next to traps (ie trap niches)
  src/mkroom.c
Labels: bug (minor)

#2093 Improve handling of arti-granted spells
  include/extern.h
  include/spell.h
  src/enlighten.c
  src/spell.c
Labels: bug (minor)

#2055 Add rcfile option to set fg color, bg color, and symbol for any template
  include/display.h
  include/extern.h
  include/flag.h
  src/display.c
  src/files.c
  src/mapglyph.c
  src/options.c
  win/curses/cursdial.c
  win/curses/cursinit.c
  win/curses/cursmain.c
  win/curses/cursstat.c
  win/share/tilemap.c
  win/tty/wintty.c
Labels: enhancement
